services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: imovelradar
      POSTGRES_PASSWORD: imovelradar
      POSTGRES_DB: imovelradar
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
